require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DealMembersController do

  # This should return the minimal set of attributes required to create a valid
  # DealMember. As you add validations to DealMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "deal_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DealMembersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all deal_members as @deal_members" do
      deal_member = DealMember.create! valid_attributes
      get :index, {}, valid_session
      assigns(:deal_members).should eq([deal_member])
    end
  end

  describe "GET show" do
    it "assigns the requested deal_member as @deal_member" do
      deal_member = DealMember.create! valid_attributes
      get :show, {:id => deal_member.to_param}, valid_session
      assigns(:deal_member).should eq(deal_member)
    end
  end

  describe "GET new" do
    it "assigns a new deal_member as @deal_member" do
      get :new, {}, valid_session
      assigns(:deal_member).should be_a_new(DealMember)
    end
  end

  describe "GET edit" do
    it "assigns the requested deal_member as @deal_member" do
      deal_member = DealMember.create! valid_attributes
      get :edit, {:id => deal_member.to_param}, valid_session
      assigns(:deal_member).should eq(deal_member)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DealMember" do
        expect {
          post :create, {:deal_member => valid_attributes}, valid_session
        }.to change(DealMember, :count).by(1)
      end

      it "assigns a newly created deal_member as @deal_member" do
        post :create, {:deal_member => valid_attributes}, valid_session
        assigns(:deal_member).should be_a(DealMember)
        assigns(:deal_member).should be_persisted
      end

      it "redirects to the created deal_member" do
        post :create, {:deal_member => valid_attributes}, valid_session
        response.should redirect_to(DealMember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved deal_member as @deal_member" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealMember.any_instance.stub(:save).and_return(false)
        post :create, {:deal_member => { "deal_id" => "invalid value" }}, valid_session
        assigns(:deal_member).should be_a_new(DealMember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealMember.any_instance.stub(:save).and_return(false)
        post :create, {:deal_member => { "deal_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested deal_member" do
        deal_member = DealMember.create! valid_attributes
        # Assuming there are no other deal_members in the database, this
        # specifies that the DealMember created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DealMember.any_instance.should_receive(:update_attributes).with({ "deal_id" => "1" })
        put :update, {:id => deal_member.to_param, :deal_member => { "deal_id" => "1" }}, valid_session
      end

      it "assigns the requested deal_member as @deal_member" do
        deal_member = DealMember.create! valid_attributes
        put :update, {:id => deal_member.to_param, :deal_member => valid_attributes}, valid_session
        assigns(:deal_member).should eq(deal_member)
      end

      it "redirects to the deal_member" do
        deal_member = DealMember.create! valid_attributes
        put :update, {:id => deal_member.to_param, :deal_member => valid_attributes}, valid_session
        response.should redirect_to(deal_member)
      end
    end

    describe "with invalid params" do
      it "assigns the deal_member as @deal_member" do
        deal_member = DealMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealMember.any_instance.stub(:save).and_return(false)
        put :update, {:id => deal_member.to_param, :deal_member => { "deal_id" => "invalid value" }}, valid_session
        assigns(:deal_member).should eq(deal_member)
      end

      it "re-renders the 'edit' template" do
        deal_member = DealMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealMember.any_instance.stub(:save).and_return(false)
        put :update, {:id => deal_member.to_param, :deal_member => { "deal_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested deal_member" do
      deal_member = DealMember.create! valid_attributes
      expect {
        delete :destroy, {:id => deal_member.to_param}, valid_session
      }.to change(DealMember, :count).by(-1)
    end

    it "redirects to the deal_members list" do
      deal_member = DealMember.create! valid_attributes
      delete :destroy, {:id => deal_member.to_param}, valid_session
      response.should redirect_to(deal_members_url)
    end
  end

end
