require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GetSignaturesController do

  # This should return the minimal set of attributes required to create a valid
  # GetSignature. As you add validations to GetSignature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "uploads_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GetSignaturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all get_signatures as @get_signatures" do
      get_signature = GetSignature.create! valid_attributes
      get :index, {}, valid_session
      assigns(:get_signatures).should eq([get_signature])
    end
  end

  describe "GET show" do
    it "assigns the requested get_signature as @get_signature" do
      get_signature = GetSignature.create! valid_attributes
      get :show, {:id => get_signature.to_param}, valid_session
      assigns(:get_signature).should eq(get_signature)
    end
  end

  describe "GET new" do
    it "assigns a new get_signature as @get_signature" do
      get :new, {}, valid_session
      assigns(:get_signature).should be_a_new(GetSignature)
    end
  end

  describe "GET edit" do
    it "assigns the requested get_signature as @get_signature" do
      get_signature = GetSignature.create! valid_attributes
      get :edit, {:id => get_signature.to_param}, valid_session
      assigns(:get_signature).should eq(get_signature)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GetSignature" do
        expect {
          post :create, {:get_signature => valid_attributes}, valid_session
        }.to change(GetSignature, :count).by(1)
      end

      it "assigns a newly created get_signature as @get_signature" do
        post :create, {:get_signature => valid_attributes}, valid_session
        assigns(:get_signature).should be_a(GetSignature)
        assigns(:get_signature).should be_persisted
      end

      it "redirects to the created get_signature" do
        post :create, {:get_signature => valid_attributes}, valid_session
        response.should redirect_to(GetSignature.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved get_signature as @get_signature" do
        # Trigger the behavior that occurs when invalid params are submitted
        GetSignature.any_instance.stub(:save).and_return(false)
        post :create, {:get_signature => { "uploads_id" => "invalid value" }}, valid_session
        assigns(:get_signature).should be_a_new(GetSignature)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GetSignature.any_instance.stub(:save).and_return(false)
        post :create, {:get_signature => { "uploads_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested get_signature" do
        get_signature = GetSignature.create! valid_attributes
        # Assuming there are no other get_signatures in the database, this
        # specifies that the GetSignature created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GetSignature.any_instance.should_receive(:update_attributes).with({ "uploads_id" => "MyString" })
        put :update, {:id => get_signature.to_param, :get_signature => { "uploads_id" => "MyString" }}, valid_session
      end

      it "assigns the requested get_signature as @get_signature" do
        get_signature = GetSignature.create! valid_attributes
        put :update, {:id => get_signature.to_param, :get_signature => valid_attributes}, valid_session
        assigns(:get_signature).should eq(get_signature)
      end

      it "redirects to the get_signature" do
        get_signature = GetSignature.create! valid_attributes
        put :update, {:id => get_signature.to_param, :get_signature => valid_attributes}, valid_session
        response.should redirect_to(get_signature)
      end
    end

    describe "with invalid params" do
      it "assigns the get_signature as @get_signature" do
        get_signature = GetSignature.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GetSignature.any_instance.stub(:save).and_return(false)
        put :update, {:id => get_signature.to_param, :get_signature => { "uploads_id" => "invalid value" }}, valid_session
        assigns(:get_signature).should eq(get_signature)
      end

      it "re-renders the 'edit' template" do
        get_signature = GetSignature.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GetSignature.any_instance.stub(:save).and_return(false)
        put :update, {:id => get_signature.to_param, :get_signature => { "uploads_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested get_signature" do
      get_signature = GetSignature.create! valid_attributes
      expect {
        delete :destroy, {:id => get_signature.to_param}, valid_session
      }.to change(GetSignature, :count).by(-1)
    end

    it "redirects to the get_signatures list" do
      get_signature = GetSignature.create! valid_attributes
      delete :destroy, {:id => get_signature.to_param}, valid_session
      response.should redirect_to(get_signatures_url)
    end
  end

end
