require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequestDocsController do

  # This should return the minimal set of attributes required to create a valid
  # RequestDoc. As you add validations to RequestDoc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "deal_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequestDocsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all request_docs as @request_docs" do
      request_doc = RequestDoc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:request_docs).should eq([request_doc])
    end
  end

  describe "GET show" do
    it "assigns the requested request_doc as @request_doc" do
      request_doc = RequestDoc.create! valid_attributes
      get :show, {:id => request_doc.to_param}, valid_session
      assigns(:request_doc).should eq(request_doc)
    end
  end

  describe "GET new" do
    it "assigns a new request_doc as @request_doc" do
      get :new, {}, valid_session
      assigns(:request_doc).should be_a_new(RequestDoc)
    end
  end

  describe "GET edit" do
    it "assigns the requested request_doc as @request_doc" do
      request_doc = RequestDoc.create! valid_attributes
      get :edit, {:id => request_doc.to_param}, valid_session
      assigns(:request_doc).should eq(request_doc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequestDoc" do
        expect {
          post :create, {:request_doc => valid_attributes}, valid_session
        }.to change(RequestDoc, :count).by(1)
      end

      it "assigns a newly created request_doc as @request_doc" do
        post :create, {:request_doc => valid_attributes}, valid_session
        assigns(:request_doc).should be_a(RequestDoc)
        assigns(:request_doc).should be_persisted
      end

      it "redirects to the created request_doc" do
        post :create, {:request_doc => valid_attributes}, valid_session
        response.should redirect_to(RequestDoc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved request_doc as @request_doc" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequestDoc.any_instance.stub(:save).and_return(false)
        post :create, {:request_doc => { "deal_id" => "invalid value" }}, valid_session
        assigns(:request_doc).should be_a_new(RequestDoc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequestDoc.any_instance.stub(:save).and_return(false)
        post :create, {:request_doc => { "deal_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested request_doc" do
        request_doc = RequestDoc.create! valid_attributes
        # Assuming there are no other request_docs in the database, this
        # specifies that the RequestDoc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RequestDoc.any_instance.should_receive(:update_attributes).with({ "deal_id" => "MyString" })
        put :update, {:id => request_doc.to_param, :request_doc => { "deal_id" => "MyString" }}, valid_session
      end

      it "assigns the requested request_doc as @request_doc" do
        request_doc = RequestDoc.create! valid_attributes
        put :update, {:id => request_doc.to_param, :request_doc => valid_attributes}, valid_session
        assigns(:request_doc).should eq(request_doc)
      end

      it "redirects to the request_doc" do
        request_doc = RequestDoc.create! valid_attributes
        put :update, {:id => request_doc.to_param, :request_doc => valid_attributes}, valid_session
        response.should redirect_to(request_doc)
      end
    end

    describe "with invalid params" do
      it "assigns the request_doc as @request_doc" do
        request_doc = RequestDoc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequestDoc.any_instance.stub(:save).and_return(false)
        put :update, {:id => request_doc.to_param, :request_doc => { "deal_id" => "invalid value" }}, valid_session
        assigns(:request_doc).should eq(request_doc)
      end

      it "re-renders the 'edit' template" do
        request_doc = RequestDoc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequestDoc.any_instance.stub(:save).and_return(false)
        put :update, {:id => request_doc.to_param, :request_doc => { "deal_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested request_doc" do
      request_doc = RequestDoc.create! valid_attributes
      expect {
        delete :destroy, {:id => request_doc.to_param}, valid_session
      }.to change(RequestDoc, :count).by(-1)
    end

    it "redirects to the request_docs list" do
      request_doc = RequestDoc.create! valid_attributes
      delete :destroy, {:id => request_doc.to_param}, valid_session
      response.should redirect_to(request_docs_url)
    end
  end

end
